#ifndef AUDIOCOMMAND_H
#define AUDIOCOMMAND_H

enum DFPlayerCommand
{
    Zero = 0,
    One = 1,
    Two = 2,
    Three = 3,
    Four = 4,
    Five = 5,
    Six = 6,
    Seven = 7,
    Eight = 8,
    Nine = 9,
    Ten = 10,
    Eleven = 11,
    Twelve = 12,
    Thirteen = 13,
    Fourteen = 14,
    Fifteen = 15,
    Sixteen = 16,
    Seventeen = 17,
    Eighteen = 18,
    Nineteen = 19,
    Twenty = 20,
    Thirty = 21,
    Fourty = 22,
    Fifty = 23,
    Sixty = 24,
    Seventy = 25,
    Eighty = 26,
    Ninety = 27,
    OneHundred = 28,
    TwoHundred = 29,
    ThreeHundred = 30,
    FourHundred = 31,
    FiveHundred = 32,
    Score = 33,
    NewHighScore = 34,
    MemoryMatching = 35,
    Simon = 36,
    LightDash = 37,
    Easy = 38,
    Medium = 39,
    Hard = 40,
    Countdown = 41,
    MuteVoiceOver = 42,
    UnmuteVoiceOver = 43,
    Mute = 44,
    Unmute = 45,
    None = 255
};

#endif